variable "rg_name" {}
variable "rg_location" {}
variable "vnet1_name" {}
variable "cider1_vnet" {}
variable "subnet1_name" {}
variable "cider3_subnet" {}
variable "vnet2_name" {}
variable "cider2_vnet" {}
variable "subnet2_name" {}
variable "cider4_subnet" {}
variable "vm_name" {}
